package project3;

import java.awt.Toolkit;
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Class:            About
 * File:              About.java
 * Description:     JDialoug pop-up that gives information about the 24 point game
 * @author        Mel Leggett
 * Environment:   PC, Windows 10, jdk 1.8, NetBeans 8.2
 * Date:         03/03/2017
 * @version         1.0
 * History Log:  03/03/2017
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class About extends javax.swing.JDialog {

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Method           About()
     * Description     called on from GUIDriver to display an about message 
     *                      for the form and adds display effects
     * @author         Mel Leggett
     * Date            03/03/2017
     * @param parent this
     * @param modal true
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public About(java.awt.Frame parent, boolean modal) 
  {
        super(parent, modal);
        //builds form
        initComponents();
        //sets form in center of screen
        this.setLocationRelativeTo(null);
        //sets close as active key (fire on Enter)
        this.getRootPane().setDefaultButton(closeJButton);
        //sets icon on top of Menu
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJPanel = new javax.swing.JPanel();
        closeJButton = new javax.swing.JButton();
        authorJLabel = new javax.swing.JLabel();
        verJLabel = new javax.swing.JLabel();
        copyJLabel = new javax.swing.JLabel();
        pictureJLabel = new javax.swing.JLabel();
        employeeJLabel = new javax.swing.JLabel();
        payJLabel = new javax.swing.JLabel();
        BalletJLabel = new javax.swing.JLabel();
        displayJScrollPane = new javax.swing.JScrollPane();
        displayJTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        backgroundJPanel.setBackground(new java.awt.Color(153, 204, 255));

        closeJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeJButton.setMnemonic('c');
        closeJButton.setText("Close");
        closeJButton.setToolTipText("close the form");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        authorJLabel.setText("Author: Mel Leggett");

        verJLabel.setText("version: 1.0");

        copyJLabel.setText("Copyright: Freeware");

        pictureJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N

        employeeJLabel.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        employeeJLabel.setText("24 Point");

        payJLabel.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        payJLabel.setText("Card Game");

        BalletJLabel.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        BalletJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BalletJLabel.setText("~ About ~");

        displayJTextArea.setEditable(false);
        displayJTextArea.setColumns(20);
        displayJTextArea.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        displayJTextArea.setLineWrap(true);
        displayJTextArea.setRows(5);
        displayJTextArea.setText("24 Point Card Game is a game popularized in Shanghai China as far back as the 1960s.  A player is dealt 4 cards.  Each card has a numerical value, the value of the card, Aces, Jacks, Queens and Kings are worth 1, 11, 12 and 13 respectively. The user then attemps to find combinations totalling 24 using all cards only once and any choice of operators(+,-,*, / ).  Players are saved uniquely and statistics are kept on each player that can be viewed from the menu.");
        displayJTextArea.setToolTipText("program description");
        displayJTextArea.setWrapStyleWord(true);
        displayJScrollPane.setViewportView(displayJTextArea);

        javax.swing.GroupLayout backgroundJPanelLayout = new javax.swing.GroupLayout(backgroundJPanel);
        backgroundJPanel.setLayout(backgroundJPanelLayout);
        backgroundJPanelLayout.setHorizontalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                .addComponent(verJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(authorJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(copyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addComponent(pictureJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeJLabel)
                            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(payJLabel))
                            .addComponent(BalletJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgroundJPanelLayout.setVerticalGroup(
            backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPanelLayout.createSequentialGroup()
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pictureJLabel))
                    .addGroup(backgroundJPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(employeeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(BalletJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPanelLayout.createSequentialGroup()
                        .addComponent(authorJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verJLabel))
                    .addComponent(closeJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        //closes about form
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalletJLabel;
    private javax.swing.JLabel authorJLabel;
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel copyJLabel;
    private javax.swing.JScrollPane displayJScrollPane;
    private javax.swing.JTextArea displayJTextArea;
    private javax.swing.JLabel employeeJLabel;
    private javax.swing.JLabel payJLabel;
    private javax.swing.JLabel pictureJLabel;
    private javax.swing.JLabel verJLabel;
    // End of variables declaration//GEN-END:variables
}
